# It isthe context execution of the teste cases
context: cpq
# It allow generate a file with the messages during the execution.
file_output: 1
# It allow shiow the messages of the execution be displayed in the console.
console_output: 0
# it is the url used for hte request. This will be drepecated in future versionusing context.
url: https://cpq-dev.cdsvisual.net
# It is the type of the request
content_type: application/json
# It is the aplication for the http requests
application: application/json
# It is the session ID of the cokens, it can be found in the cookie
SessionID: 25E0730F0A35F39133EFCF189B43D71F
# It is the token used to the 
token: 
